# Development commands for audit. Tools come from devbox (`devbox shell`, or
# direnv); CI runs each recipe as its own job.

export GOWORK := "off"

# Format all Go files
fmt:
    golangci-lint fmt ./...

# Regenerate everything from the proto: Go, the published JSON Schema, and
# TypeScript. The TypeScript plugin is fetched from the schema registry, so this
# needs the network.
generate:
    buf generate

# Regenerate only what local plugins produce: Go, and the record's JSON Schema.
generate-local:
    buf generate --template buf.gen.local.yaml

# Generated code is committed. A change to the proto that is not followed by
# `just generate` leaves the tree dirty here.
#
# The gate checks only what local plugins produce, so that it needs nothing but
# this checkout: the TypeScript plugin comes from a remote registry that rate
# limits, and a gate that fails because somebody else was generating code is a
# gate people learn to ignore. `drift-ts` is the same check for TypeScript and
# belongs in CI, where a retry is cheap.
drift: generate-local sentences
    git diff --exit-code -- gen ts/src/catalogue

# The common catalogue's sentences, for the viewer in @truvity/audit. Generated
# from catalogue/common.yaml so the two cannot drift: `drift` fails on a diff.
sentences:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p ts/src/catalogue
    {
        echo '// Code generated by `just sentences` from catalogue/common.yaml. DO NOT EDIT.'
        echo 'import type { Sentences } from "../sentences.js";'
        echo
        printf 'export const common: Sentences = '
        go run ./cmd/audit messages catalogue/common.yaml
    } > ts/src/catalogue/common.ts

drift-ts: generate
    git diff --exit-code -- gen ts/src/gen

# Lint proto and check that nothing released has changed incompatibly
proto:
    buf lint
    # A first release has nothing to be incompatible with, and saying so beats
    # a recipe that always passes because its comparison silently failed.
    if tag=$(git describe --tags --abbrev=0 2>/dev/null); then \
        buf breaking --against ".git#tag=$tag"; \
    else \
        echo "no release tag yet: nothing to compare against"; \
    fi

# Build (compile check)
build: fmt
    go build ./...

# Run unit tests
test:
    go test ./... -coverprofile=coverage.out

# Run the whole suite against a real Postgres.
#
# The index is the one part of this repository that cannot be tested without a
# database, and mocking it would prove nothing about the idempotency that is its
# whole contract. So those tests skip when AUDIT_POSTGRES_URL is unset: a
# contributor without Postgres still runs everything else, and `check` stays
# hermetic. This runs the whole suite rather than `./index/...`, because the
# writer's end-to-end tests need the database too.
# CI runs this as its own job with a service container.
#
# This starts a Postgres under .devbox, initialising it on first use.
test-postgres:
    #!/usr/bin/env bash
    set -euo pipefail
    export PGDATA="$PWD/.devbox/virtenv/postgresql/data"
    export PGHOST="$PWD/.devbox/virtenv/postgresql"
    mkdir -p "$PGHOST"
    [ -d "$PGDATA/base" ] || initdb -U postgres --auth=trust >/dev/null
    pg_ctl status -D "$PGDATA" >/dev/null 2>&1 || \
        pg_ctl -D "$PGDATA" -o "-k $PGHOST -c listen_addresses=" -l "$PGHOST/log" start -w
    createdb -h "$PGHOST" -U postgres audit_test 2>/dev/null || true
    AUDIT_POSTGRES_URL="postgres://postgres@/audit_test?host=$PGHOST" go test ./...

# Stop the Postgres that `test-postgres` started
stop-postgres:
    pg_ctl stop -D "$PWD/.devbox/virtenv/postgresql/data" || true

# The S3 image the archive-walk tests run against.
#
# Pinned by digest, and deliberately not `latest` or `stable`: those now resolve
# to LocalStack's licensed build and exit 55 without a token, which in a public
# repository means every fork's CI fails with a licensing message its author
# cannot fix. The community edition is the 4.x line; the current CalVer releases
# are the licensed ones. The tests take an endpoint rather than a product
# (`AUDIT_S3_URL`), so swapping this for MinIO or a real bucket is a variable,
# not a change.
s3_image := "localstack/localstack@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a"

# Run the archive-walk tests against a real S3.
#
# These are the tests that would have caught the two bugs the memory store hid:
# a digest covering one tenant, and a listing stopping at the first thousand
# keys. They skip when AUDIT_S3_URL is unset, so `check` stays hermetic.
test-s3:
    #!/usr/bin/env bash
    set -euo pipefail
    docker rm -f audit-s3 >/dev/null 2>&1 || true
    docker run -d --name audit-s3 -p 4566:4566 -e SERVICES=s3,kms {{s3_image}} >/dev/null
    trap 'docker rm -f audit-s3 >/dev/null 2>&1 || true' EXIT
    for i in $(seq 1 40); do
        curl -sf -m 3 http://localhost:4566/_localstack/health >/dev/null 2>&1 && break
        sleep 3
    done
    AUDIT_S3_URL=http://localhost:4566 go test ./internal/s3test/... ./store/...

# The OpenBAO the transit key provider and signer are tested against. Pinned
# by digest for the reason the S3 image is: a moving tag changes the test.
openbao_image := "openbao/openbao@sha256:597f62847dd382382056a1d6704d50465908c2040038c4611832a23269a67112"

# The whole suite with every service it can use: Postgres, S3 with object
# locking, and an OpenBAO dev server. Every test that skips without its service
# runs here — the searchers' conformance suite against all three searchers, the
# transports' corpus, the archive walks, the transit keys and signer, and the
# read-only conformance run against an embedded query service. A few minutes;
# not part of `check`, which needs nothing but the checkout. CI runs it as its
# own job.
conformance:
    #!/usr/bin/env bash
    set -euo pipefail
    export PGDATA="$PWD/.devbox/virtenv/postgresql/data"
    export PGHOST="$PWD/.devbox/virtenv/postgresql"
    mkdir -p "$PGHOST"
    [ -d "$PGDATA/base" ] || initdb -U postgres --auth=trust >/dev/null
    pg_ctl status -D "$PGDATA" >/dev/null 2>&1 || \
        pg_ctl -D "$PGDATA" -o "-k $PGHOST -c listen_addresses=" -l "$PGHOST/log" start -w
    createdb -h "$PGHOST" -U postgres audit_test 2>/dev/null || true

    docker rm -f audit-s3 audit-bao >/dev/null 2>&1 || true
    trap 'docker rm -f audit-s3 audit-bao >/dev/null 2>&1 || true' EXIT
    docker run -d --name audit-s3 -p 4566:4566 -e SERVICES=s3,kms {{s3_image}} >/dev/null
    docker run -d --name audit-bao -p 8200:8200 -e BAO_DEV_ROOT_TOKEN_ID=root \
        {{openbao_image}} server -dev -dev-listen-address=0.0.0.0:8200 >/dev/null
    for i in $(seq 1 40); do
        curl -sf -m 3 http://localhost:4566/_localstack/health >/dev/null 2>&1 && \
            curl -sf -m 3 http://localhost:8200/v1/sys/health >/dev/null 2>&1 && break
        sleep 3
    done

    AUDIT_POSTGRES_URL="postgres://postgres@/audit_test?host=$PGHOST" \
    AUDIT_S3_URL=http://localhost:4566 \
    AUDIT_OPENBAO_URL=http://localhost:8200 AUDIT_OPENBAO_TOKEN=root \
        go test -count=1 ./...

# Run the tests under the race detector. The emitter hands records to a
# background writer, so a data race there would be a lost or duplicated record
# rather than a crash, and would not show up in an ordinary run.
#
# This is not part of `check`, and deliberately. Everything else in this
# repository builds with cgo off, which is what makes the binaries static and
# the images small; the race detector is the one thing that needs a C
# toolchain. Putting it in the gate would mean every contributor needs one to
# run the gate at all. CI runs this as its own job, where the toolchain is the
# runner's own.
race:
    CGO_ENABLED=1 go test -race ./...

# Run linters
lint:
    golangci-lint config verify
    golangci-lint run ./...
    goreleaser check
    # Nothing built is committed. A binary in a public repository's history
    # is in every clone forever, and carries the build machine's paths. The
    # largest source file here is under 100 KiB; 1 MiB is a build output.
    ! git ls-files -s | awk '{print $2" "$4}' | git cat-file --batch-check='%(objectsize) %(rest)' | awk '$1 > 1048576 {print "too large to be source:", $2; found=1} END {exit !found}'
    # A `;` inside a mermaid sequenceDiagram is a statement separator: it
    # splits the message and GitHub renders nothing. Keep them out of docs.
    ! grep -rn --include=*.md -E '^[[:space:]]*[A-Za-z][A-Za-z0-9_]*[[:space:]]*-?->>?.*;' docs/

# Hold this repository's own presets and catalogue to the contracts it publishes,
# and hold this repository's own code to its catalogue the way an adopter's is
# held. The second line lists every action the common catalogue declares that
# nothing here emits yet; each is a job for a later milestone, and the digest
# jobs' events sat on that list unnoticed until the tool was pointed at home.
schemas:
    go run ./cmd/audit validate --presets presets catalogue/common.yaml
    go run ./cmd/audit check-emitters . --catalogue catalogue/common.yaml

# Hold the chart to what the binaries will accept.
#
# The golden renders are committed, so a template change that alters a manifest
# shows up as a diff a reviewer reads rather than as a surprise in a cluster.
# The refusals matter more: each is a configuration the binaries reject at
# start-up, or accept and then get quietly wrong, and a chart that renders one
# anyway moves the failure somewhere nobody is looking.
chart:
    helm lint charts/audit -f charts/audit/testdata/values/stream.yaml
    bash charts/audit/testdata/refuse.sh
    helm template audit charts/audit -f charts/audit/testdata/values/direct.yaml \
        > charts/audit/testdata/golden/direct.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/stream.yaml \
        > charts/audit/testdata/golden/stream.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/transit.yaml \
        > charts/audit/testdata/golden/transit.yaml
    git diff --exit-code -- charts/audit/testdata/golden

# The TypeScript package: install, typecheck, test, build, and check what a
# publish would ship. Not part of `check`, which needs nothing but the
# checkout: this fetches from the npm registry. CI runs it as its own job.
ts:
    cd ts && npm ci --no-audit --no-fund
    cd ts && npx tsc --noEmit
    cd ts && npx vitest run
    cd ts && rm -rf dist && npx tsc -p tsconfig.build.json
    # What a publish from the root would ship: the compiled package, and no
    # test or test helper. The root's prepare script is what builds the
    # package when it is installed from a git commit; it has just run above.
    npm pack --dry-run --ignore-scripts --json | grep -q '"path": "ts/dist/react/index.js"'
    ! npm pack --dry-run --ignore-scripts --json | grep -E '"path": "ts/dist/.*(test|testing)'

# Build everything a release would, locally and unpublished: the archives and,
# through ko, the two images the chart deploys. Not part of `check`: it builds
# for every platform and is minutes, not seconds.
snapshot:
    goreleaser release --snapshot --clean

# This repository is public and its history cannot be unpublished — a rewrite
# changes the SHAs but not what was already fetched. So the rule (nothing here
# names a real cluster, account, host or ticket) is enforced mechanically
# rather than remembered.
leak-canary:
    hack/leak-canary.sh

# Run Go vulnerability check
vuln:
    govulncheck ./...

# Everything CI runs
check: build test lint proto drift schemas chart leak-canary vuln
