# Development commands for audit. Tools come from devbox (`devbox shell`, or
# direnv); CI runs each recipe as its own job.

export GOWORK := "off"

# Format all Go files
fmt:
    golangci-lint fmt ./...
    cd sdk && golangci-lint fmt ./...

# Regenerate everything from the proto: Go, the published JSON Schema, and
# TypeScript. The TypeScript plugin is fetched from the schema registry, so this
# needs the network.
generate:
    buf generate

# Regenerate only what local plugins produce: Go, and the record's JSON Schema.
generate-local:
    buf generate --template buf.gen.local.yaml

# Generated code is committed. A change to the proto that is not followed by
# `just generate` leaves the tree dirty here.
#
# The gate checks only what local plugins produce, so that it needs nothing but
# this checkout: the TypeScript plugin comes from a remote registry that rate
# limits, and a gate that fails because somebody else was generating code is a
# gate people learn to ignore. `drift-ts` is the same check for TypeScript and
# belongs in CI, where a retry is cheap.
drift: generate-local sentences config-schemas
    git diff --exit-code -- gen sdk/gen ts/src/catalogue schemas/config charts/audit/values.schema.json

# The JSON Schema of each binary's configuration file, written into
# schemas/config/ from internal/config/schema, and the chart's values schema,
# which embeds them under each component's `config`. The binaries embed the
# first and Helm reads the second; `drift` fails when either is not what this
# writes.
config-schemas:
    go run ./internal/config/gen

# The common catalogue's sentences, for the viewer in @truvity/audit. Generated
# from sdk/catalogue/common.yaml so the two cannot drift: `drift` fails on a diff.
sentences:
    #!/usr/bin/env bash
    set -euo pipefail
    mkdir -p ts/src/catalogue
    {
        echo '// Code generated by `just sentences` from sdk/catalogue/common.yaml. DO NOT EDIT.'
        echo 'import type { Sentences } from "../sentences.js";'
        echo
        printf 'export const common: Sentences = '
        go run ./cmd/audit messages sdk/catalogue/common.yaml
    } > ts/src/catalogue/common.ts

drift-ts: generate
    git diff --exit-code -- gen sdk/gen ts/src/gen

# Lint proto and check that nothing released has changed incompatibly
proto:
    buf lint
    # A first release has nothing to be incompatible with, and saying so beats
    # a recipe that always passes because its comparison silently failed.
    if tag=$(git describe --tags --abbrev=0 --match 'v*' 2>/dev/null); then \
        buf breaking --against ".git#tag=$tag"; \
    else \
        echo "no release tag yet: nothing to compare against"; \
    fi

# Build (compile check). The repository is two Go modules: the root, and the
# consumer SDK in sdk/. Each is built on its own, which is how a consumer of the
# SDK builds it: with no sight of the root.
build: fmt
    go build ./...
    cd sdk && go build ./...

# Run unit tests
test:
    go test ./... -coverprofile=coverage.out
    cd sdk && go test ./... -coverprofile=coverage.out
    # One profile for the coverage report: the SDK's, without its header line.
    tail -n +2 sdk/coverage.out >> coverage.out && rm sdk/coverage.out

# Run the whole suite against a real Postgres.
#
# The index is the one part of this repository that cannot be tested without a
# database, and mocking it would prove nothing about the idempotency that is its
# whole contract. So those tests skip when AUDIT_POSTGRES_URL is unset: a
# contributor without Postgres still runs everything else, and `check` stays
# hermetic. This runs the whole suite rather than `./index/...`, because the
# writer's end-to-end tests need the database too.
# CI runs this as its own job with a service container.
#
# This starts a Postgres under .devbox, initialising it on first use.
test-postgres:
    #!/usr/bin/env bash
    set -euo pipefail
    export PGDATA="$PWD/.devbox/virtenv/postgresql/data"
    export PGHOST="$PWD/.devbox/virtenv/postgresql"
    mkdir -p "$PGHOST"
    [ -d "$PGDATA/base" ] || initdb -U postgres --auth=trust >/dev/null
    pg_ctl status -D "$PGDATA" >/dev/null 2>&1 || \
        pg_ctl -D "$PGDATA" -o "-k $PGHOST -c listen_addresses=" -l "$PGHOST/log" start -w
    createdb -h "$PGHOST" -U postgres audit_test 2>/dev/null || true
    AUDIT_POSTGRES_URL="postgres://postgres@/audit_test?host=$PGHOST" go test ./...

# Stop the Postgres that `test-postgres` started
stop-postgres:
    pg_ctl stop -D "$PWD/.devbox/virtenv/postgresql/data" || true

# The S3 image the archive-walk tests run against.
#
# Pinned by digest, and deliberately not `latest` or `stable`: those now resolve
# to LocalStack's licensed build and exit 55 without a token, which in a public
# repository means every fork's CI fails with a licensing message its author
# cannot fix. The community edition is the 4.x line; the current CalVer releases
# are the licensed ones. The tests take an endpoint rather than a product
# (`AUDIT_S3_URL`), so swapping this for MinIO or a real bucket is a variable,
# not a change.
s3_image := "localstack/localstack@sha256:3ebc37595918b8accb852f8048fef2aff047d465167edd655528065b07bc364a"

# Run the archive-walk tests against a real S3, and the SQS sink against a real
# SQS: LocalStack serves both.
#
# These are the tests that would have caught the two bugs the memory store hid:
# a digest covering one tenant, and a listing stopping at the first thousand
# keys. They skip when AUDIT_S3_URL is unset, so `check` stays hermetic.
test-s3:
    #!/usr/bin/env bash
    set -euo pipefail
    docker rm -f audit-s3 >/dev/null 2>&1 || true
    docker run -d --name audit-s3 -p 4566:4566 -e SERVICES=s3,kms,sqs {{s3_image}} >/dev/null
    trap 'docker rm -f audit-s3 >/dev/null 2>&1 || true' EXIT
    for i in $(seq 1 40); do
        curl -sf -m 3 http://localhost:4566/_localstack/health >/dev/null 2>&1 && break
        sleep 3
    done
    AUDIT_S3_URL=http://localhost:4566 AUDIT_SQS_URL=http://localhost:4566 go test ./internal/s3test/... ./store/... ./sink/sqssink/...

# The OpenBAO the transit key provider and signer are tested against. Pinned
# by digest for the reason the S3 image is: a moving tag changes the test.
openbao_image := "openbao/openbao@sha256:597f62847dd382382056a1d6704d50465908c2040038c4611832a23269a67112"

# The whole suite with every service it can use: Postgres, S3 with object
# locking, and an OpenBAO dev server. Every test that skips without its service
# runs here — the searchers' conformance suite against all three searchers, the
# transports' corpus, the archive walks, the transit keys and signer, and the
# read-only conformance run against an embedded query service. A few minutes;
# not part of `check`, which needs nothing but the checkout. CI runs it as its
# own job.
conformance:
    #!/usr/bin/env bash
    set -euo pipefail
    export PGDATA="$PWD/.devbox/virtenv/postgresql/data"
    export PGHOST="$PWD/.devbox/virtenv/postgresql"
    mkdir -p "$PGHOST"
    [ -d "$PGDATA/base" ] || initdb -U postgres --auth=trust >/dev/null
    pg_ctl status -D "$PGDATA" >/dev/null 2>&1 || \
        pg_ctl -D "$PGDATA" -o "-k $PGHOST -c listen_addresses=" -l "$PGHOST/log" start -w
    createdb -h "$PGHOST" -U postgres audit_test 2>/dev/null || true

    docker rm -f audit-s3 audit-bao >/dev/null 2>&1 || true
    trap 'docker rm -f audit-s3 audit-bao >/dev/null 2>&1 || true' EXIT
    docker run -d --name audit-s3 -p 4566:4566 -e SERVICES=s3,kms,sqs {{s3_image}} >/dev/null
    docker run -d --name audit-bao -p 8200:8200 -e BAO_DEV_ROOT_TOKEN_ID=root \
        {{openbao_image}} server -dev -dev-listen-address=0.0.0.0:8200 >/dev/null
    for i in $(seq 1 40); do
        curl -sf -m 3 http://localhost:4566/_localstack/health >/dev/null 2>&1 && \
            curl -sf -m 3 http://localhost:8200/v1/sys/health >/dev/null 2>&1 && break
        sleep 3
    done

    AUDIT_POSTGRES_URL="postgres://postgres@/audit_test?host=$PGHOST" \
    AUDIT_S3_URL=http://localhost:4566 \
    AUDIT_OPENBAO_URL=http://localhost:8200 AUDIT_OPENBAO_TOKEN=root \
        go test -count=1 ./...

# Run the tests under the race detector. The emitter hands records to a
# background writer, so a data race there would be a lost or duplicated record
# rather than a crash, and would not show up in an ordinary run.
#
# This is not part of `check`, and deliberately. Everything else in this
# repository builds with cgo off, which is what makes the binaries static and
# the images small; the race detector is the one thing that needs a C
# toolchain. Putting it in the gate would mean every contributor needs one to
# run the gate at all. CI runs this as its own job, where the toolchain is the
# runner's own.
race:
    CGO_ENABLED=1 go test -race ./...
    cd sdk && CGO_ENABLED=1 go test -race ./...

# Run linters
lint:
    golangci-lint config verify
    golangci-lint run ./...
    cd sdk && golangci-lint run ./...
    goreleaser check
    # Nothing built is committed. A binary in a public repository's history
    # is in every clone forever, and carries the build machine's paths. The
    # largest source file here is under 100 KiB; 1 MiB is a build output.
    ! git ls-files -s | awk '{print $2" "$4}' | git cat-file --batch-check='%(objectsize) %(rest)' | awk '$1 > 1048576 {print "too large to be source:", $2; found=1} END {exit !found}'
    # A `;` inside a mermaid sequenceDiagram is a statement separator: it
    # splits the message and GitHub renders nothing. Keep them out of docs.
    ! grep -rn --include=*.md -E '^[[:space:]]*[A-Za-z][A-Za-z0-9_]*[[:space:]]*-?->>?.*;' docs/

# The consumer SDK must stay small. It is a module of its own (sdk/) so that
# an emitter's dependency graph holds what an emitter needs and not what the
# writer and the query service need: no database driver, no stream server, no
# object store, no OpenBao, no OpenTelemetry SDK or exporter, no JWT library.
# This lists the packages the SDK builds, refuses to pass on an empty list, and
# fails on any package from the forbidden set, naming it. The set is a deny
# list and not an allow list so that a Renovate bump of a dependency the SDK
# already has is never a failure; a NEW heavy dependency is.
sdk-closure:
    #!/usr/bin/env bash
    set -euo pipefail
    cd sdk
    deps=$(go list -deps ./... | sort -u)
    count=$(grep -c . <<<"$deps")
    # The SDK has dozens of packages of its own and its dependencies; an empty
    # or tiny list means the listing failed, not that the closure is clean.
    if [ "$count" -lt 50 ]; then
        echo "sdk-closure: only $count packages listed; the check scanned nothing" >&2
        exit 1
    fi
    forbidden='^(github.com/jackc/|github.com/nats-io/|github.com/aws/|github.com/klauspost/|github.com/lestrrat-go/|github.com/truvity/(gateway-auth|access-roster|gemaal|policy|ocictl)|go.opentelemetry.io/otel/(sdk|exporters)|go.opentelemetry.io/contrib/|google.golang.org/(grpc|genproto)|helm.sh/|github.com/openbao/|github.com/hashicorp/|k8s.io/|github.com/truvity/audit/(authn|sinkserver|writer|index|store|query|wire|cmd|internal))'
    # The module's own path is github.com/truvity/audit/sdk; anything else
    # under github.com/truvity/audit/ is the root module.
    bad=$(grep -E "$forbidden" <<<"$deps" || true)
    if [ -n "$bad" ]; then
        echo "sdk-closure: the SDK depends on server-only packages:" >&2
        echo "$bad" >&2
        exit 1
    fi
    echo "sdk-closure: $count packages, none server-only"

# Hold this repository's own presets and catalogue to the contracts it publishes,
# and hold this repository's own code to its catalogue the way an adopter's is
# held. The second line lists every action the common catalogue declares that
# nothing here emits yet; each is a job for a later milestone, and the digest
# jobs' events sat on that list unnoticed until the tool was pointed at home.
schemas:
    go run ./cmd/audit validate --presets presets sdk/catalogue/common.yaml
    go run ./cmd/audit check-emitters . --catalogue sdk/catalogue/common.yaml

# Hold the chart to what the binaries will accept.
#
# The golden renders are committed, so a template change that alters a manifest
# shows up as a diff a reviewer reads rather than as a surprise in a cluster.
# The refusals matter more: each is a configuration the binaries reject at
# start-up, or accept and then get quietly wrong, and a chart that renders one
# anyway moves the failure somewhere nobody is looking. And the chart passes
# each component's `config` through unchanged, which `go test ./charts/audit`
# holds it to: every rendered ConfigMap is the values' block, and a file its
# binary's schema accepts.
chart:
    helm lint charts/audit -f charts/audit/testdata/values/stream.yaml
    AUDIT_REQUIRE_HELM=1 go test -count=1 ./charts/audit/
    bash charts/audit/testdata/refuse.sh
    helm template audit charts/audit -f charts/audit/testdata/values/direct.yaml \
        > tests/golden/audit/direct.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/stream.yaml \
        > tests/golden/audit/stream.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/transit.yaml \
        > tests/golden/audit/transit.yaml
    # The attested tier on an S3-compatible store: no lock, an endpoint, path
    # style, static credentials, and an exports bucket on a store of its own.
    helm template audit charts/audit -f charts/audit/testdata/values/attested.yaml \
        > tests/golden/audit/attested.yaml
    # The two shapes the deployment pages document, rendered from the very
    # files those pages show. The values above are trial installs with no
    # index, so without these the migration hook -- which only exists when
    # there is a database -- is never rendered at all.
    helm template audit charts/audit -f charts/audit/examples/direct.yaml \
        > tests/golden/audit/example-direct.yaml
    helm template audit charts/audit -f charts/audit/examples/stream.yaml \
        > tests/golden/audit/example-stream.yaml
    helm template audit charts/audit -f charts/audit/examples/sqs.yaml \
        > tests/golden/audit/example-sqs.yaml
    # The two other things the chart renders, each alone: the alert rules and
    # the Grafana dashboards (`renders: alerts`, `renders: dashboards`).
    helm lint charts/audit -f charts/audit/testdata/values/alerts.yaml
    helm lint charts/audit -f charts/audit/testdata/values/dashboards.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/alerts.yaml \
        > tests/golden/audit/alerts.yaml
    helm template audit charts/audit -f charts/audit/testdata/values/dashboards.yaml \
        > tests/golden/audit/dashboards.yaml
    # A hook Pod whose service account the chart creates normally is admitted
    # and then never scheduled: only an install finds that, so assert it here.
    for shape in direct stream transit attested example-direct example-stream example-sqs; do \
        python3 charts/audit/testdata/hook-order.py \
            < tests/golden/audit/$shape.yaml; \
    done
    git diff --exit-code -- tests/golden/audit

# The release of VictoriaMetrics' vmutils whose `vmalert-tool` runs the rule
# tests: the one truvity/observability's stack chart pins for its ruler, so the
# rules are proven on the engine that will evaluate them. Fetched with its
# published checksum verified, as truvity/observability's rulecheck fetches its
# parsers.
vmutils_version := "v1.152.0"

# The release of truvity/observability whose `dashboardlint` is the dashboard
# contract (docs/dashboards.md there), run by `go run` at this pinned version.
observability_version := "v0.43.3"

# The alert rules and the dashboard, held to the observability contract: the
# generated dashboard is the committed one, passes the dashboard lint (and the
# lint is shown to refuse a dashboard pinned to a datasource, so it is not a
# check that passes whatever it is given), and every rule fires on what it
# should and stays silent on what it should not, on vmalert-tool. Needs the
# network for the two pinned tools. CI runs this as its own recipe.
telemetry:
    #!/usr/bin/env bash
    set -euo pipefail
    python3 hack/dashboards/audit-overview.py | diff - charts/audit/dashboards/audit-overview.json

    tools=$(mktemp -d); trap 'rm -rf "$tools"' EXIT
    GOBIN="$tools" go install github.com/truvity/observability/cmd/dashboardlint@{{observability_version}}
    "$tools/dashboardlint" charts/audit/dashboards/*.json
    # The refusal is real: the same dashboard with a literal datasource must fail.
    sed 's/"uid": "${datasource}"/"uid": "a-literal-uid"/' charts/audit/dashboards/audit-overview.json > "$tools/pinned.json"
    if "$tools/dashboardlint" "$tools/pinned.json" 2>"$tools/pinned.err"; then
        echo "dashboardlint accepted a dashboard pinned to one datasource" >&2; exit 1
    fi
    grep -q "literal datasource" "$tools/pinned.err"

    os=$(uname -s | tr '[:upper:]' '[:lower:]')
    case "$(uname -m)" in x86_64) arch=amd64 ;; aarch64|arm64) arch=arm64 ;; *) echo "no vmutils for $(uname -m)" >&2; exit 1 ;; esac
    tarball="vmutils-$os-$arch-{{vmutils_version}}.tar.gz"
    base="https://github.com/VictoriaMetrics/VictoriaMetrics/releases/download/{{vmutils_version}}"
    cache="${XDG_CACHE_HOME:-$HOME/.cache}/audit/vmutils-{{vmutils_version}}-$os-$arch"
    if [ ! -x "$cache/vmalert-tool-prod" ]; then
        mkdir -p "$cache"
        curl -fsSL "$base/$tarball" -o "$tools/$tarball"
        curl -fsSL "$base/${tarball%.tar.gz}_checksums.txt" -o "$tools/sums.txt"
        (cd "$tools" && grep " $tarball\$" sums.txt | sha256sum -c -)
        tar -xzf "$tools/$tarball" -C "$cache" vmalert-tool-prod
    fi
    AUDIT_REQUIRE_HELM=1 AUDIT_REQUIRE_VMALERT=1 AUDIT_VMALERT_TOOL="$cache/vmalert-tool-prod" go test -count=1 ./charts/audit/

# The TypeScript package: install, typecheck, test, build, and check what a
# publish would ship. Not part of `check`, which needs nothing but the
# checkout: this fetches from the npm registry. CI runs it as its own job.
ts:
    cd ts && npm ci --no-audit --no-fund
    cd ts && npx tsc --noEmit
    cd ts && npx vitest run
    cd ts && rm -rf dist && npx tsc -p tsconfig.build.json
    # What a publish from the root would ship: the compiled package, and no
    # test or test helper. The root's prepare script is what builds the
    # package when it is installed from a git commit; it has just run above.
    npm pack --dry-run --ignore-scripts --json | grep -q '"path": "ts/dist/react/index.js"'
    ! npm pack --dry-run --ignore-scripts --json | grep -E '"path": "ts/dist/.*(test|testing)'

# Build everything a release would, locally and unpublished: the archives and,
# through ko, the two images the chart deploys. Not part of `check`: it builds
# for every platform and is minutes, not seconds.
snapshot:
    goreleaser release --snapshot --clean

# This repository is public and its history cannot be unpublished — a rewrite
# changes the SHAs but not what was already fetched. So the rule (nothing here
# names a real cluster, account, host or ticket) is enforced mechanically
# rather than remembered.
leak-canary:
    hack/leak-canary.sh

# Assemble the schema site into a scratch directory: proves every published
# schema's $id is the URL it is served at.
pages:
    hack/pages-site.sh "$(mktemp -d)/site"

# Run Go vulnerability check
vuln:
    govulncheck ./...
    cd sdk && govulncheck ./...

# The kind tier: this repository owns no cluster of its own — it installs
# onto truvity/policy's box (see that repository's hack/kind/), the second
# public repository to (docs/guides/testing.md has the full case). In CI the
# shared integration workflow stands the box up itself, via truvity/ci-actions'
# `cluster` action; on a laptop, stand truvity/policy's own box up first
# (`just cluster` there) and point KCTX/E2E_KCTX at it if it is not
# `kind-policy`.

# Build this repository's images and package its chart exactly as a release
# does, one architecture, into the box's own registry.
[doc("Build the images and chart exactly as a release does, into the local registry")]
e2e-snapshot:
    bash hack/e2e-snapshot.sh

# Stand in for the platform: the database and its two roles, the stream, the
# archive bucket and the digest chain's signing key, under the exact names
# charts/audit/testdata/values/e2e.yaml gives the chart. Must run before
# `e2e-install`.
[doc("Provision what a platform would, by name")]
e2e-fixture:
    bash e2e/fixture/apply.sh

# Install the PACKAGED chart `e2e-snapshot` produced — never the source
# directory — on top of what `e2e-fixture` provisioned.
[doc("Install the chart into the local cluster")]
e2e-install:
    #!/usr/bin/env bash
    set -euo pipefail
    KCTX=${KCTX:-kind-policy}
    NS=${NS:-audit-e2e}
    RELEASE=${RELEASE:-audit-e2e}
    CHART_TGZ=${CHART_TGZ:-$(find dist/charts -name 'audit-*.tgz' 2>/dev/null | sort -V | tail -1)}
    if [ -z "$CHART_TGZ" ]; then
        echo "no packaged chart under dist/charts — run 'just e2e-snapshot' first" >&2
        exit 1
    fi
    kubectl --context "$KCTX" get namespace "$NS" >/dev/null 2>&1 || kubectl --context "$KCTX" create namespace "$NS"
    # A hook that fails is kept for debugging, and so are its pods, which is the
    # only place a failed migration says why: print them before giving up.
    if ! helm --kube-context "$KCTX" upgrade --install "$RELEASE" "$CHART_TGZ" -n "$NS" \
        -f charts/audit/testdata/values/e2e.yaml \
        --wait --timeout 8m; then
        echo "--- the release did not install; what the cluster says ---" >&2
        kubectl --context "$KCTX" -n "$NS" get pods,jobs >&2 || true
        kubectl --context "$KCTX" -n "$NS" describe jobs,pods >&2 || true
        kubectl --context "$KCTX" -n "$NS" logs -l "app.kubernetes.io/instance=$RELEASE" \
            --all-containers --prefix --tail=200 >&2 || true
        exit 1
    fi
    kubectl --context "$KCTX" -n "$NS" get pods

# Prove the chart works end to end — a Go suite
# (e2e/suite), reaching every Service through
# github.com/truvity/gemaal/pkg/harness. E2E_NAMESPACE turns it on;
# `go test ./...` (`just test`) stays hermetic without it.
[doc("Prove the chart works end to end")]
e2e-smoke:
    E2E_NAMESPACE="${NS:-audit-e2e}" E2E_RELEASE="${RELEASE:-audit-e2e}" \
        go test ./e2e/suite/... -count=1 -v

# The whole kind tier, from a snapshot build to the suite.
[doc("The whole kind tier, from a snapshot build to the suite")]
e2e-all: e2e-snapshot e2e-fixture e2e-install e2e-smoke

# Everything CI runs. `vuln` is deliberately not here: a new CVE in a
# dependency must not turn this gate red on a PR that never touched it. Run
# `just vuln` on its own to check.
check: build test lint proto drift schemas chart telemetry leak-canary pages sdk-closure
