// Code generated by `just sentences` from catalogue/common.yaml. DO NOT EDIT.
import type { Sentences } from "../sentences.js";

export const common: Sentences = {
  "source": "audit",
  "version": "1.0.0",
  "locales": [
    "en"
  ],
  "actions": {
    "audit.catalogue.registered": {
      "summary": "A source registered a catalogue version.",
      "message": {
        "en": "{actor} registered catalogue {targets.0.id}"
      }
    },
    "audit.clock.synchronised": {
      "summary": "The daily clock-synchronisation check ran.",
      "message": {
        "en": "clock on {observer.instance} synchronised with UTC, offset {data.offset_ms} ms"
      }
    },
    "audit.digest.failed": {
      "summary": "Digest verification failed.",
      "message": {
        "en": "digest window {targets.0.id} FAILED verification: {outcome.reason}"
      }
    },
    "audit.digest.verified": {
      "summary": "A digest chain window was verified.",
      "message": {
        "en": "digest window {targets.0.id} verified"
      }
    },
    "audit.digest.written": {
      "summary": "An hourly digest was signed and written.",
      "message": {
        "en": "digest {targets.0.id} written covering {data.objects} objects"
      }
    },
    "audit.export.completed": {
      "summary": "An export job finished and its signed URL was issued.",
      "message": {
        "en": "export {targets.0.id} completed with {data.records} records"
      }
    },
    "audit.export.requested": {
      "summary": "An export job was started.",
      "message": {
        "en": "{actor} requested an export of the {profile} profile"
      }
    },
    "audit.facets": {
      "summary": "Facet counts were read for a profile.",
      "message": {
        "en": "{actor} read facets of the {profile} profile"
      }
    },
    "audit.get": {
      "summary": "One record was read by id.",
      "message": {
        "en": "{actor} read record {targets.0.id}"
      }
    },
    "audit.hold.placed": {
      "summary": "A legal hold was placed.",
      "message": {
        "en": "{actor} placed hold {targets.0.id}"
      }
    },
    "audit.hold.released": {
      "summary": "A legal hold was released.",
      "message": {
        "en": "{actor} released hold {targets.0.id}"
      }
    },
    "audit.key.destroyed": {
      "summary": "A pseudonymisation key was destroyed, unlinking its pseudonyms.",
      "message": {
        "en": "{actor} destroyed key {targets.0.id}"
      }
    },
    "audit.preset.changed": {
      "summary": "A preset version in use changed.",
      "message": {
        "en": "{actor} changed preset {targets.0.id}"
      }
    },
    "audit.profile.changed": {
      "summary": "A profile's composition or retention changed.",
      "message": {
        "en": "{actor} changed profile {targets.0.id}"
      }
    },
    "audit.pseudonym.resolved": {
      "summary": "A pseudonym was resolved back to the identity behind it.",
      "message": {
        "en": "{actor} resolved pseudonym {targets.0.id}"
      }
    },
    "audit.retention.extended": {
      "summary": "The lock on an object holding an earlier record was lengthened because a later record relies on it.",
      "message": {
        "en": "the lock on record {targets.0.id} was lengthened for record {targets.1.id}"
      }
    },
    "audit.search": {
      "summary": "A search was executed against a profile.",
      "message": {
        "en": "{actor} searched the {profile} profile"
      }
    },
    "audit.writer.dead_lettered": {
      "summary": "A record could not be processed and was written to the dead-letter prefix.",
      "message": {
        "en": "record {targets.0.id} dead-lettered: {outcome.reason}"
      }
    },
    "audit.writer.started": {
      "summary": "A split writer instance started.",
      "message": {
        "en": "writer {observer.instance} started"
      }
    },
    "audit.writer.stopped": {
      "summary": "A split writer instance stopped.",
      "message": {
        "en": "writer {observer.instance} stopped"
      }
    }
  }
}
